Armazenamento de metadados gerados durante pipeline de dados
splor-mg/cookiecutter-datapackage pull request #37
Opened 2024-03-20 22:33 UTC by labanca

closes #31 
- Implementa funcoes `write_dict_to_json` e `add_metadata_to_json` para armazenar metadados
- Durante etapa de `build` adiciona os metados gerados ao `datapackage.json`

2024-03-21 11:23 UTC, fjuniorr requested changes
O PR veio vazio.

2024-03-22 14:15 UTC, labanca reviewed
Corrigido no commit https://github.com/splor-mg/cookiecutter-datapackage/pull/37/commits/c87bb937844f922902909a547e406ae940ce7991.

2024-03-25 16:54 UTC, fjuniorr commented
A parte do `scripts/build.py` é isso mesmo. 

Pra registro, inicialmente eu tinha falado pra gente salvar os metadados customizados na raiz de cada recurso e não na propriedade `metadata`. Mas @labanca observou bem que como esses metadados são opcionais e não vão existir em todos os recursos, diferentemente do que acontece com o `update_at` na raiz do data package, é uma forma conveniente de "bater o olho" e ver se existem metadados opcionais que estão sendo inseridos durante a etapa de build.

Um problema de fluxo que não vejo solução e podemos deixar do jeito que está é que alterações no arquivos de log não vão gerar uma nova etapa do make build porque não estão no Makefile.

## write_dict_to_json e add_metadata_to_json

Aqui vejo duas questões: 

1. Eu consigo ver a utilidade de facilitar a escrita/leitura de json, mas pra facilitar o reuso nos projetos acho melhor colocar elas no `dpm` do que como scripts aqui no cookiecutter.
1. Em termos da API você não prefere um par `read_json(path: Path)` e `write_json(data: dict, path: Path)` e as outras manipulações ficam no próprio script de ETL?

2024-03-26 18:19 UTC, labanca commented
> 2\. Em termos da API você não prefere um par `read_json(path: Path)` e `write_json(data: dict, path: Path)` e as outras manipulações ficam no próprio script de ETL?

Creio que não entendi o que foi sugerido aqui. Eu fiz duas funções pensando no uso simplificado para o usuário mesmo. Ele não precisar se preocupar com manipulações e somente criar o dicionário ou o par chave:valor que ele quer inserir no json para uma resource específica. Você está sugerindo trocar somente pela função que lida com dicionários?

Quando a  `read_json(path: Path)` seria criar uma função no DPM para ler json e retornar um dicionário?

2024-03-26 21:38 UTC, fjuniorr commented
> Creio que não entendi o que foi sugerido aqui. Eu fiz duas funções pensando no uso simplificado para o usuário mesmo. Ele não precisar se preocupar com manipulações e somente criar o dicionário ou o par chave:valor que ele quer inserir no json para uma resource específica. Você está sugerindo ter um tipo de função que lida somente com dicionários?
> 
> Quando a `read_json(path: Path)` seria criar uma função no DPM para ler json e retornar um dicionário?

Pode fazer merge deste PR e a gente continua a discussão dessas aqui em um PR no DPM.

Acho que vai ser bom a gente ter que efetivamente salvar JSON no fluxo de ETL pra mostrar quais funções vão ser mais convenientes.

2024-03-26 21:39 UTC, fjuniorr approved these changes

2024-03-27 01:28 UTC, merged